figure;

load('target_stream_for_figure.mat')
subplot(4,1,1);plot(tVec,newTargetSound,'k')
ylim([-0.7,0.7])
yticklabels({''})
xticklabels({''})
load('unscrambled_masker_for_figure.mat')
subplot(4,1,2);plot(tVec,newMaskerSound,'k')
ylim([-0.7,0.7])
yticklabels({''})
xticklabels({''})
load('scrambled_masker_for_figure.mat')
subplot(4,1,3);plot(tVec,newMaskerSound,'k')
ylim([-0.7,0.7])
yticklabels({''})
xticklabels({''})
load('scrambled_AM_masker_for_figure.mat')
subplot(4,1,4);plot(tVec,newMaskerSound*1.4,'k')
ylim([-0.7,0.7])
yticklabels({''})
hold on;plot(tVec,this_masker_envelope*max(newMaskerSound)/max(this_masker_envelope),'r')